# Generated by Django 4.2.9 on 2024-01-10 12:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mainpage', '0003_booking_no_of_guests'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='restaurant',
            options={'ordering': ['city']},
        ),
    ]
