# Generated by Django 4.2.9 on 2024-01-10 12:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mainpage', '0004_alter_restaurant_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='booking',
            options={'ordering': ['restaurant', '-booked_on']},
        ),
    ]
