# Generated by Django 4.2.9 on 2024-01-11 10:20

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mainpage', '0006_alter_booking_options_alter_booking_additional_notes'),
    ]

    operations = [
        migrations.AddField(
            model_name='restaurant',
            name='featured_image',
            field=cloudinary.models.CloudinaryField(default='placeholder', max_length=255, verbose_name='image'),
        ),
    ]
