# Generated by Django 4.2.9 on 2024-01-11 12:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainpage', '0007_restaurant_featured_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='restaurant',
            name='slug',
            field=models.SlugField(max_length=100, null=True, unique=True),
        ),
    ]
