# Generated by Django 4.2.9 on 2024-01-11 12:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mainpage', '0008_restaurant_slug'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='restaurant',
            options={'ordering': ['city', 'name']},
        ),
    ]
