# Generated by Django 4.2.9 on 2024-01-11 13:18

from django.conf import settings
import django.contrib.auth.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('mainpage', '0009_alter_restaurant_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='restaurant',
            name='author',
            field=models.ForeignKey(default=django.contrib.auth.models.User, on_delete=django.db.models.deletion.CASCADE, related_name='restaurant_posts', to=settings.AUTH_USER_MODEL),
        ),
    ]
